### ISSUE TITLE
USER STORY: Django project setup 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#10]
As a **Developer** I can **setup a new Django project and apps** so that **I can create the basic project structure**.

# Acceptance Criteria: 
1. Manage.py file and main directory created.
2. Python manage.py runserver completes successfully, showing success page when opened in browser.
3. Env file is present and contains secret key variable.
4. Env.py is included in git ignore file.
5. Settings file has been updated to include template setup and import env file. 

# Tasks:
- [x] Create Django project (django-admin startproject main . ).
- [x] Create Django apps (python manage.py startapp <app name>) and add them to the settings.py file
- [x] Apply initial migrations (python manage.py migrate)
- [x] Create a env.py file to store sensitive information. Add os import and environ variable SECRET_KEY to env.py.
- [x] Add the env.py file to the .gitignore file so that sensitive information is never committed.
- [x] Update settings.py to import env file and SECRET_KEY

**Comment by GaryDolan** [comment]
Set up project, apps and config files.
