### ISSUE TITLE
USER STORY: Initial Heroku deployment

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#12]
As a **developer** I can **deploy my project to Heroku** so that **I can confirm correct operation early in the project**.

# Acceptance Criteria: 
1. Deployment completes with no issues.
2. Open App button from Heroku dashboard shows success page.

# Tasks:
- [x] Create a new Heroku app pokemon-tcg-ireland
- [x] Add DATABASE_URL,  SECRET_KEY and PORT (8000) config vars.
- [x] Add a DISABLE_COLLECTSTATIC environment var with a value of one (just for initial deployment)
- [x] Add Heroku host-name (pokemon-tcg-ireland.herokuapp.com) to allowed hosts in settings.py. Also add 'localhost', '127.0.0.1', '127.0.0.1:8000'.
- [x] Create a Procfile to tell Heroku to use the gunicon webserver.
- [x] Create a runtime.txt file to tell heroku to deploy using python-3.10.6 (ensures send mail function will work)
- [x] Commit and push all changes, Deploy the Heroku project using GitHub

**Comment by GaryDolan** [comment]
Initial Heroku completed
