### ISSUE TITLE
USER STORY: Social network and footer links

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#15]
As a **user** I can **click on the websites social links in the footer** so that **I can visit the stores various social networks and interact with them**.

# Acceptance Criteria: 
1. Social network icons are displayed in footer and are clearly visible.
2. Social network icons are clickable and open the correct network.
3. All social networks are opened in new tabs.
4. Hover animation works correctly for all icons. 

# Tasks:
- [x] Add social network icons to the footer for Facebook, Instagram, Twitter, YouTube and LinkedIn.
- [x] Add quick access links to footer for about us, contact us, shipping details and privacy policy.
- [x] Ensure all links are clearly viable and visually appealing.
- [x] Add hoover animation and colour change to the links in CSS.
- [x] Implement hyperlink functionality for the links, linking them correctly.
- [x] Ensure links to external sites open in a new tab.

**Comment by GaryDolan** [comment]
Footer added
