### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#22]
As a **user** I can **logout** so that **I can no longer access my account and associated functionality**.

# Acceptance Criteria: 
1. Log out button should send user to page or display modal that asks if they are sure they wish to log out.
2. Upon log out the user should be directed to the home page and no longer have access to facilities such as their profile etc.

# Tasks:
- [x] Wire up nav bar link in base template for logout.
- [x] Modify allauth template for logout so that it suits out websites needs.
- [x] Ensure user is presented with the log out confirmation page or modal.  
- [x] Ensure user is redirected to home page after log out.

**Comment by GaryDolan** [comment]
Logout complete and tested
