### ISSUE TITLE
USER STORY: Email confirmation

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#24]
As a **user** I can **receive a sign up confirmation email** so that **I can verify my account sign up was successful**

# Acceptance Criteria: 
1. Upon signup user will be redirected to the verify email address page.
2. User will receive an email with a link to verify their email address.
 
# Tasks:
- [x] Add email settings to settings.py so that allauth can send emails.
- [x] Update relevant allauth templates that are related to account verification.
- [x] Update email templates where neccessary.

**Comment by GaryDolan** [comment]
Email verification setup and working correctly.
