### ISSUE TITLE
USER STORY: User Profile 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#26]
As a **user** I can **view my profile page** so that **I can edit my account info (address etc.)**.

# Acceptance Criteria: 
1. Profile is accessible via the nav bar link.
2. Profile displays all user sections for order history, password change, address update and product wish list.
3. Profile content is retrieved correctly and displayed dynamically when accessed.
4. Profile nav bar link is only available to logged in users.

# Tasks:
- [x] Create a Django model and associated methods for a profile, using the ERD for reference.
- [x] Add user profile to order model in checkout models.
- [x] Make migrations for new models including a dry run (--dry-run).
- [x] Migrate changes to database, including a plan check (--plan)
- [x] Wire up link in nav bar for user profile page (only if logged in)
- [x] Create user profile form to edit information.
- [x] Create a user profile template, displaying forms to update user info, password and displaying wishlist and recent orders.
- [x] Update checkout successful template so it can be used to show old order confirmations.
- [x] Create a view for the user profile.
- [x] Wire up user profile URL.
- [x] Implement error handling if user info cannot be retrieved
- [x] Add security so that the profile is only available if logged in and username matches profile

**Comment by GaryDolan** [comment]
User profile has been completed and contains all relevant sections.
