### ISSUE TITLE
USER STORY: View wishlist

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#30]
As a **user** I can **view my wish-list** so that **I can purchase item which I saved to it earlier**

# Acceptance Criteria: 
1. View wish-list button is available on the user profile page.
2. Clicking wish-list button will display the users to the wish-list.
3. Wish-list on profile page will display all items that the user has added to their wish-list.  
4. Items can be selected from the wish-list to be viewed and purchased.
5. Heart icon beside each item can be selected to remove the item from the wish-list.

# Tasks:
- [x] Update profile view to retrieve and return the products in the users wish-list.
- [x] Add wish-list collapse to the user profile template 
- [x] Add the wish-list to profile template
- [x] Add a delete from wish-list icon (heart) to each product on the profile page so the user can remove items from the list.

**Comment by GaryDolan** [comment]
User can view and update wish-list from profile
