### ISSUE TITLE
USER STORY: View a list of products

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#32]
As a **shopper** I can **view a list products** so that **I can choose whats ones I would like to purchase**

# Acceptance Criteria: 
1. Nav bar leads to products page
2. The products page of the website displays a list of all the products.
3. All product data is rendered dynamically and correct.

# Tasks:
- [x] Create a view for the products list.
- [x] Create a products page template to render the view, showing all relevant details of each product.
- [x] Connect up the URL in the products app urls.py.
- [x] Link nav bar item to products.

**Comment by GaryDolan** [comment]
Products page has been created
