### ISSUE TITLE
USER STORY: View the details of a product 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#33]
As a **shopper** I can **click on a product in the list** so that **I can view full details such as price, features, description, images, warnings, reviews**

# Acceptance Criteria: 
1. Clicking on a product link opens the full product view with all relevant images and details.
2. All product data is rendered dynamically and correctly.

# Tasks:
- [x] Create a view for the detailed product page.
- [x] Create a HTML template which displays the products details.
- [x] Connect up the URL in products app urls.py.
- [x] Include URL in main django projects url.py
- [x] Link clickable items in the product lists to their corresponding product so that when a product link is clicked the correct product page is displayed.

**Comment by GaryDolan** [comment]
Product detailed view created, add to basket button etc. will be added when doing relevant sections.
