### ISSUE TITLE
USER STORY: Add items to my wishlist 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#36]
As a **shopper** I can **add products to my wish-list** so that **I can save products that I wish to purchase at a later date.**

# Acceptance Criteria: 
1. Heart icon is rendered on product detail user is logged in.
2. No heart icon is rendered if not logged in.
3. When logged in, the user can interact with wish-list icon and toggle icon from outline to solid adding/removing product from their list.
 
 
# Tasks:
- [x] Create a wish-list app, model and view
- [x] Add a form (heart icon) to product details page to allow users to add the product to their wish-list.
- [x] Add a signal to create a user profile wish-list when a new user is registered.

**Comment by GaryDolan** [comment]
Wish-list has been added and tested
