### ISSUE TITLE
USER STORY: Add products

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#38]
As a **superuser** I can **add a product** so that **I can add products to my online store**

# Acceptance Criteria: 
1. Products, categories, cardset and expansion models all appear in the admin panel.
2. All fixtures have been loaded correctly and all instances of them appear in the correct models.
3. Manage products appears in my acc dropdown when super user is logged in and leads to manage products page.
4. User can use form to add new products

# Tasks:
- [x] Add product,category, cardset and expansion models to products app.
- [x] Add models to admin.py
- [x] Obtain and add images for products
- [x] Create fixtures for models.
- [x] Load fixtures
- [x] Install summernote (pip3 install django-summernote) and update requirements.txt.
- [x] Add sumernote to list of installed apps in settings.py and add its URL to url.py
- [x] Update admin.py to set post description field to use summernote.
- [x] Make migrations for new models including a dry run (--dry-run).
- [x] Migrate changes to database, including a plan check (--plan)
- [x] Add link in my account drop down for manage products that only shows when a super user is logged in.
- [x] Link nav bar item to manage products.
- [x] Add form to products app and create products form.
- [x] Add a view , url and template for add_products, update view to handle post request and create products

**Comment by GaryDolan** [comment]
Admin user can now add products from the front end
