### ISSUE TITLE
USER STORY: Edit products

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#39]
As a **superuser** I can **edit a product** so that **I can change the details of an existing product, including name, description, images, price, product code, category and others**

# Acceptance Criteria: 
1. From either the products page or product details page the user can access the edit button.
2. The user will be shown an edit product page, where they can see and edit all the products info.
3. Upon completion of the product edit the user will be returned to the product detail page fro that product and updates will be applied.
 
# Tasks:
- [x] Add edit product url
- [x] Add edit product that displays a form for user to update product
- [x] Write a view for edit product that returns form to template and processes POST request.

**Comment by GaryDolan** [comment]
Edit product functionality added and operational
