### ISSUE TITLE
USER STORY: Delete a product

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#40]
As a **superuser** I can **delete a product** so that **I can remove items which are no longer available to purchase.**

# Acceptance Criteria: 
1. From either the products page or product details page the user can access the delete button.
2. The user will be shown a confirmation modal, where they can select delete or cancel.
3. Upon selecting cancel they will be returned the item will not be deleted, if delete is selected the item will be deleted and the use will be returned to the products page.
 
# Tasks:
- [x] Add delete product url.
- [x] Update product and product detail template to include a delete button
- [x] Add confirmation modal.
- [x] Add a delete view to handle deleting the product from the db.

**Comment by GaryDolan** [comment]
Product deletion working correctly with modal
