### ISSUE TITLE
USER STORY: Sort products

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#43]
As a **shopper** I can **sort the list of available products** so that **I can view products based on a number of criteria such as name price, rating, category, set, expansion**

# Acceptance Criteria: 
1. Sort by price link sorts products by price ascending. 
2. Sort by rating link sorts products by rating descending.
3. Sort by category link sorts products by category name ascending.

# Tasks:
- [x] Add dropdown menu links from all products with links to sort by price, rating and category.
- [x] Add url and query to all links. 
- [x] Update view to handle sort queries.

**Comment by GaryDolan** [comment]
Sorting added and operating as expected.
