### ISSUE TITLE
USER STORY: Sort multiple catagories

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#45]
As a **shopper** I can **sort multiple product categories at the same time** so that **I can find items in multiple categories at the same time**

# Acceptance Criteria: 
1. Sort selector is present and defaults to the correct text based on the value of current sorting
2. All sort options work correctly and sort the items based on the selected option. 

# Tasks:
- [x] Add sort selector to products page
- [x] Ensure the sort selector selected attribute defaults to the correct text when the page is loaded based on the value of current sorting
- [x] Add javascript to sort products based on the selection made in the sort selector

**Comment by GaryDolan** [comment]
Sort selector fully functional and working correctly
