### ISSUE TITLE
USER STORY: Search products

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#46]
As a **shopper** I can **search for products by name and description** so that **I can find a products which I would like to purchase**

# Acceptance Criteria: 
1. Header contains search bar.
2. Search button is appended to search bar.
3. Search button contains icon.
4. Form action is linked to the products page.

# Tasks:
- [x] Add a search bar form to the header so user can input text.
- [x] Append a search button to the form input.
- [x] Add a search icon to the button.
- [x] Link form action.
- [x] update products view to handle the get request.

**Comment by GaryDolan** [comment]
Search functionality added, some fine tuning needed such as finding whole word only. This has been noted and will be added at a later time.
