### ISSUE TITLE
USER STORY: Display search results 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#47]
As a **shopper** I can **see my search results and the number of them** so that **I can see if a product I have searched for is available**

# Acceptance Criteria: 
1. User can enter a search query and press enter or the search icon to initiate the search. 
2. Products page is displayed showing products with search term in their name or description.
3. Search term is displayed on the products page so the user can identify what they have searched for.
4. Number of items returned is shown on the products page.

# Tasks:
- [x] Complete user story #46 
- [x] Update products page to display the search text the user entered.
- [x] Update the products page to display the number of items returned by the search

**Comment by GaryDolan** [comment]
Search functionality is functional and count and text now display when search carried out
