### ISSUE TITLE
USER STORY: View shopping cart

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#50]
As a **shopper** I can **view the items I have added to my cart** so that **I can see a summary of my intended purchases**

# Acceptance Criteria: 
1. User can add items to shopping cart
2. User can view shopping cart via icon in top nav
3. All items added to cart are displayed with total cost delivery etc.

# Tasks:
- [x] Create cart app and add to installed apps in settings.py
- [x] Create cart views to process adding  items etc
- [x] Create  cart template 
- [x] Add urls and add this to main url
- [x] Add cart link to top nav and mobile top nav
- [x] Add context.py file with context processor and add to main settings.
- [x] Add free shipping threshold and std delivery price vars to settings
- [x] Add form and inputs to product details template to select quantity and add item to cart

**Comment by GaryDolan** [comment]
Shopping basket is operational and works as expected
