### ISSUE TITLE
USER STORY: Edit shopping bag

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#51]
As a **shopper** I can **change the quantity of items in my shopping bag** so that **I can make adjustments to the products I wish to purchase before I checkout**

# Acceptance Criteria: 
1. User can add or remove a single item from the shopping basket using + and - buttons.
2. User can adjust value via direct form entry.
3. Customer can remove a product completely by using the x icon on the product.
4. Qty all update as expected including total and subtotals.

# Tasks:
- [x] Add form to shopping basket for item qty.
- [x] Add + and - icons that inc and dec qty and submit form on press (custom js).
- [x] Add JS to capture if enter (13) is pressed and submit the form with the correct value.
- [x] Ensure direct form entry is bound between 1 and 99.
- [x] Add an x icon to the product details section to allow product removal.
- [x] Add view to handle product qty adjustments and removal, including urls.

**Comment by GaryDolan** [comment]
Shopping bag fully completed and working as expected
