### ISSUE TITLE
USER STORY: Checkout payment info

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#52]
As a **shopper** I can **enter my payment information** so that **I can pay for my items at checkout**

# Acceptance Criteria: 
1. User can view checkout page from checkout button in basket.
2. User can enter required information in the checkout form and form validation works correctly.
3. Users can select their country from a dropdown in the form.
4. Users can enter their credit card information
5. Users can see a summary of their order including all products and costs.

# Tasks:
- [x] Create models for order and order line line item.
- [x] Create template for checkout displaying order form and line item details.
- [x] Add checkout view and URL
- [x] Create order and order line item admin classes for use in the panel.
- [x] Add signals.py and add listner functions to update the order total when an item its added or deleted from an order. 
- [x] Update apps.py to let django know there is a new signals.py with listeners in it.
- [x] Create the chekout form in a new forms.py
- [x] Install crispy forms for use when displaying the form (pip3 install django-crispy-forms==1.14.0)
- [x] Update requirements.txt (pip3 freeze –local > requirements.txt).

**Comment by GaryDolan** [comment]
Checkout added and functioning correctly
