### ISSUE TITLE
USER STORY: Payments & Secure info

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#53]
As a **shopper** I can **be sure my information is secure** so that **I am happy to provide all information to make a purchase**

# Acceptance Criteria: 
1. Customers can enter their credit card info into a strip element on the checkout page.
2. Invalid entries will be flagged in form.
3. Customers will be sent to a payment successful page upon successful payment.
4. Overlay will hide page when payment is being processed.
5. 

# Tasks:
- [x] Install stripe pip3 install stripe and update requirements.
- [x] Import stripe into checkout view.
- [x] Add stripe currency
- [x] Add stripe public key, secret key to the env file and import to settings file.
- [x] Add div to hold strip element to checkout template and give it an id to target.
- [x] Import stripe JS in base template.
- [x] Add the JS for stripe payments to checkout app static JS folder. 
- [x] Add JS event listener to handle validation errors on the card element.
- [x] Add JS event listener to handle form submission
- [x] Add a custom css file to checkout apps static folder and add css for stripe element. 
- [x] Link css file to checkout template.
- [x] Import basket contents function from basket context.py to checkout view, use it to get the basket total cost for creating stripe intent.
- [x] Create a stripe payment intent in checkout view.
- [x] Return the the public key and client secret from view and retrieve at the end of checkout using json_script filter.
- [x] Update view to handle form submission and create order and line items if form is valid.
- [x] Set the default app config in the init.py file to ensure signals from app.py work 
- [x] Add page overlay upon form submission.
- [x] Add webhook view(webhooks.py) and url. This will call a webhook handler based on the returned webhook from stripe.
- [x] Add webhook_handler.py and use stripe webhooks (like django signals) to ensure order is always created if payment is successful.
- [x] Add a new view to views.py to add extra metadata to the the payment intent. This view will be called before confirm card payment is submitted and will allow us to have access to all the order info including save_info tick box in the webhooks returned from stripe.
- [x] Add 2 new fields original basket and stripe pid to the order model, used to ensure user can place the same order more than once.
- [x] Install django countries and add it to the countries field in our form. This insures a correct country code is submitted to stripe.

**Comment by GaryDolan** [comment]
Stripe added and fully functional.
