### ISSUE TITLE
USER STORY: Receive a confirmation emails after a purchase 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#55]
As a **shopper** I can **receive a confirmation emails after a purchase** so that **I know my order has been placed and I have a copy of my purchases**

# Acceptance Criteria: 
1. Confirmation email received after a successful order placed.
2. Email confirms order number item details, user address etc
 
# Tasks:
- [x] Create confirmation email body and subject txt files 
- [x] Update the webhook handler with function to send email using txt files
- [x] Update webhook handler to send email anytime an order is successful.
- [x] Update settings.py with email details.

**Comment by GaryDolan** [comment]
Confirmation email implemented successfully
