### ISSUE TITLE
USER STORY: Robots.txt 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#57]
As a **developer** I can **create a robots.txt** so that **I can control the access search engine crawlers have to parts of my website.**

# Acceptance Criteria: 
1. robots.txt added to the project root
2. robots.txt contains user-agent: *, disallow commands and the sitemap URL

# Tasks:
- [x] Add a robots.txt to the project root
- [x] Add the command User-agent: * to the robots.txt
- [x] Add Disallow commands to stop the search engine crawling specific parts of the website.
- [x] Add the sitemap URL to the the end of the robots.txt

**Comment by GaryDolan** [comment]
robots.txt created populated and added to root.
