### ISSUE TITLE
USER STORY: Marketing page

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#59]
As a **developer** I can **create a facebook page for marketing, promoting and showcasing my website to potential customers** so that **I can direct potential customers to my website.**

# Acceptance Criteria: 
1. Facebook marketing page has been created with all business details and imagery.
2. Facebook page is accessible via the link in the footer 

# Tasks:
- [x] Create Business page using Facebook.
- [x] Add all relevant details and imagery.
- [x] Post about our website including URL to direct users to it.
- [x] Take screen shots for read me in case the page is deactivated

**Comment by GaryDolan** [comment]
Facebook page created to use for marketing and added to the website footer.
