### ISSUE TITLE
USER STORY: Meta tags and SEO

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#60]
As a **developer** I can **ensure meta tags keywords etc are used** so that **the correct content can be easily accessed.**

# Acceptance Criteria: 
1. Keywords added to meta data in head and description added that uses keywords.
2. Any external links use no opener and no follow rel attributes.
3. Key word added to headings and strong tags where possible. 
4. All image names and alt attributes are descriptive and use keywords where possible.
5. All content is high quality, useful and bolsters a sense of authority and trustworthiness. 

# Tasks:
- [x] Add rel attributes of noopener and nofollow to external links to ensure opened pages have no access to our site and web crawlers do not follow the link.
- [x] Add an about us page to foster trust in the website and make it clear to users and search engines exactly who we are and what we do.
- [x] Use the about us page as a way to add keywords tastefully and link to an external partner with a high value website. 
- [x] Add keywords where possible without interrupting the flow of content or content usefulness. Focus on heading and strong tags.
- [x] Add all keywords to meta tag in base and also add a meta description which uses some keywords tastefully.
- [x] Ensure image names and alts are relevant to the image and use keywords where possible.

**Comment by GaryDolan** [comment]
Completed.
