### ISSUE TITLE
USER STORY: Newsletter

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#61]
As a **user** I can **I can sign up to the newsletter** so that **I can be kept up to date with the latest product releases and offers**

# Acceptance Criteria: 
1. Newsletter signup is available in the footer. User can enter email address to subscribe.

# Tasks:
- [x] Sign up for mailchimp.
- [x] Create an embedded signup form.
- [x] Add the code to my project, separating out js, css, html into relevant places.        
- [x] Customise the form and style.

**Comment by GaryDolan** [comment]
Newsletter signup created and added to the project.
