### ISSUE TITLE
USER STORY: Automated validation

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#68]
As a **developer** I can **carry out validation of my code** so that **I can ensure it complies to coding guidelines**.

# Acceptance Criteria: 
1. All Validators passed with no errors.

# Tasks:
- [x]  Use the W3C HTML validator to validate HTML, fixing any error which arise.
- [x]  Use the W3C CSS validator to validate the CSS, fixing any error which arise.
- [x] Use the JSHint tool to validate the JavaScript, fixing any error which arise.
- [x] Use the code institutes Pep8 linter to validate the python code, fixing any error which arise.

**Comment by GaryDolan** [comment]
Testing completed for all languages and all changes made
