### ISSUE TITLE
USER STORY: Plan apps

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#7]
As a **developer** I can **decided on what individual apps my project will contain** so that **I can separate my code into different apps based on their functionality**

# Acceptance Criteria: 
1. Project contains a Main app.
2. Project contains a Home app.
3. Project contains a Profiles app.
4. Project contains a Products app.
5. Project contains a Cart app.
6. Project contains a Checkout app.
7. Project contains a Privacy policy app.
8. Project contains an About us app.
9. Project contains a Contact us app.
10. Project contains a Shipping details app.

# Tasks:
- [x] Create Django apps (python manage.py startapp <app name>) and add them to the settings.py file
- [x] Create Main app.
- [x] Create Home app.
- [x] Create Profiles app.
- [x] Create Products app.
- [x] Create Cart app.
- [x] Create Checkout app.
- [x] Create Privacy policy app.
- [x] Create About us app.
- [x] Create Contact us app.
- [x] Create Shipping details app.

**Comment by GaryDolan** [comment]
Apps have been planned and created.
