### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#72]
As a **user** I can **view a home page** so that **I can be introduced to the store and its products**

# Acceptance Criteria: 
1. Home page contains a hero image, intro text and a shop now button.
2. Shop now button will direct the user to the product page.
3. Home page will contain a popular products section (based on customer ratings) and newest arrivals based on date products were added.

# Tasks:
- [x] Create a homepage template.
- [x] Add hero image, intro text and shop now button.
- [x] Create a homepage URL.
- [x] Create a homepage view to display the newest and most popular products.
- [x]  Link products to their product detail views .

**Comment by GaryDolan** [comment]
Home page complete with new and popular products
