### ISSUE TITLE
USER STORY: Privacy policy 

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#73]
As a **user** I can **view the websites privacy policy** so that **I can understand how my information is used**

# Acceptance Criteria: 
1. Privacy policy is accessible via the site footer.
2. Policy page contains info regarding personal data use and users rights.

# Tasks:
- [x] Create a privacy policy template.
- [x] Add info to the page regarding data used. 
- [x] Link footer to privacy policy page.

**Comment by GaryDolan** [comment]
Privacy policy created.
