### ISSUE TITLE
USER STORY: About us page

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#74]
As a **user** I can **view an about us page** so that **I can learn all about the company**.

# Acceptance Criteria: 
1. About us page is accessible via the footer.
2. About us page provides user with details of the company.
3. About us page contains a find us section, containing a google map to the company location.   

# Tasks:
- [x] Create an about us page template and URL 
- [x] Create an about us page view.
- [x] Add company info to the about use page.
- [x] Add find us section and google map to the about us page.
- [x]  Link footer to about us page.

**Comment by GaryDolan** [comment]
Added about us page, with highlighted keyword.
