### ISSUE TITLE
USER STORY: Contact us form

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#75]
As a **user** I can **fill out a contact form** so that **I can communicate with the website owner directly**.

# Acceptance Criteria: 
1. User can access a contact us page via the footer.
2. Contact us page is a form which the user can fill out to contact the company directly.
3. Contact populates relevant fields based on if the user is logged in or not. 

# Tasks:
- [x] Create contact us model with all relevant fields
- [x] Create contact us template and form 
- [x] Create a contact us view and url, add it to the main URLS.
- [x] Populate relevant fields based on if the user is logged in or not.
- [x] Add model to the admin panel and add functions for admin to set contact as replied and resolved.
- [x] Use django email service to send the users query directly to the club email address.

**Comment by GaryDolan** [comment]
Contact us form completed and working correctly
