### ISSUE TITLE
USER STORY: Shipping details

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#76]
As a **user** I can **view a shipping details page** so that **I can learn about how order shipping works.**

# Acceptance Criteria: 
1. Shipping details page is accessible via link footer.
2. Shipping details page provides user with details of the how order shipping works.

# Tasks:
- [ ] Create an shipping page template and URL.
- [ ] Create an shipping page view.
- [ ] Add shipping info to the shipping details page.
- [ ] Link in footer directs user to shipping page.
