### ISSUE TITLE
USER STORY: Messaging

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#77]
As a **developer** I can **add messaging to the website** so that **I can provide the user with feedback regarding the action they have performed**.

# Acceptance Criteria: 
1. Messages function correctly and are displayed in the correct location.
2. Messages will timeout and remove themselves from the page.

# Tasks:
- [x] In the settings.py file import messages and set up message tags.
- [x] Update base.html to display messages.
- [x] Add toast templates.
- [x] Add messaging to any relevant user actions that would require them.
- [x] Creates an account.
- [x] Logs into an account.
- [x] Logs out of an account.
- [x] Adds /removes item to basket.
- [x] Updating item quantity of item in basket.
- [x] Adds / removes item to wish list.
- [x] Editing address.
- [x] Editing password.
- [x] Adding a product success .
- [x] Adding a product failure (blank textfield)
- [x] Editing a product. 
- [x] Editing a product success.
- [x] Adding a product failure.
- [x] Deleting a product. 
- [x] Submitting a review.
- [x] Submitting a review failure.
- [x] Deleting a review.
- [x] Trying to delete someone else's review via direct url entry. 
- [x] Item not found during checkout.
- [x] Checkout form incorrectly filled out. 
- [x] Failed payment processing.
- [x] Successful order completion.
- [x] Completion of the contact us form.
- [x] No search text entered when searching.
- [x] When trying to access the add/edit/delete product view when not an admin (should never occur, unless they knew the url).
- [x] Editing profile info.
- [x] Editing profile info failure. 
- [x] Editing profile shipping info .
- [x] Edit profile shipping info failure.
- [x] Edit profile password.
- [x] Edit profile password failure.
- [x] Viewing order history.

**Comment by GaryDolan** [comment]
Messaging completed and tested
