### ISSUE TITLE
USER STORY: Final deployment

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#79]
As a **developer** I can **carry out my final deployment** so that **my website deploys correctly to Heroku**

# Acceptance Criteria: 
1. Website should look exactly as it did when running locally as we are now using the same database. 
2. All functionality should be the same as the local website.

# Tasks:
- [x] In env.py, set DEVELOPMENT to False so that in settings.py it will set the debug flag to FALSE.
- [x] Remove disable_collectstatic from the Heroku config vars.
- [x] Set x frame options so that summernote works when project is deployed.
- [x] Remove DEVELOPMENT from Heroku config vars, if present.
- [x] Use Heroku app URL to create a stripe webhook and obptain the secret key, add this as a config var.
- [x] Deploy branch.
- [x] Open app to ensure it works correctly.
- [x] Setup and configure AWS.
- [x] Install boto3 (pip3 install boto3).
- [x] Install django storages (pip3 django storages) and add to installed app in settings.
- [x] Add s3 settings to settings.py to tell it which bucket it should be communicating with.
- [x] Add USE_AWS, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to Heroku config vars.
- [x] Create custom_storage.py and set it up to store static and media files in ASW suing settings added to settings.py.
- [x] Add S3 object parameters to settings.py.
- [x] Upload images to S3 bucket.
- [x] Add stripe public, secret and wh secrete to cofig vars

**Comment by GaryDolan** [comment]
Completed
