### ISSUE TITLE
USER STORY: Product Review

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#80]
As a **user** I can **submit a review on a product** so that **other site users can quickly gauge my opinion of the product**

# Acceptance Criteria: 
1. When logged in each product detail page will have a review section.
2. To review the product user must select a star rating and add a message.
3. Once submitted the review is sent for approval and the the review section is replaced with a message thanking the user for their review.
4. If not logged in a message is displayed asking the user to log in or register to review the product.
5. Once approved the users review will be displayed along with all others.
6. Once displayed the logged in user can delete their review using a delete button beside their review.
7. Admin can accept, reject or perform crud functions on all reviews. 

# Tasks:
- [x] Add review model to products app 
- [x] Add views for adding and deleting reviews from the DB.
- [x] Add URLs for add and delete review. 
- [x] Add review form and display this form on the product details page (if logged in), allowing user to review this item.
- [x] Add all reviews related to this product below the product form and include a link to delete users own review.
- [x] Add functions to product model to allow average rating and review count to be calculated, use these to display the number of stars, average rating and number of ratings on the product details page (link to reviews below)
- [x] Add average rating for products to all product cards.
- [x] Add reviews to the admin panel and add function to allow admin to approve or reject reviews.

**Comment by GaryDolan** [comment]
Reviews added to project and working as intended.
