### ISSUE TITLE
USER STORY: Notifications

### ISSUE THREAD

**Issue by GaryDolan** [GaryDolan/ci-p5-pokemon-tcg-ireland#84]
As a **user** I can **see messages whenever I perform an action** so that **I can know if my actions were successful, caused errors etc.**

# Acceptance Criteria: 
1. User receives toasts for adding or removing products.
2. User receives toasts for updating details or if errors occur.
3. Messages display for 
- [x] Adding item to the bag
- [x] Updating item quantity from product details
- [x] Updating qty from basket
- [x] Empty search

# Tasks:
- [x] Use django messages framework and bootstrap toasts to implement user messaging.
- [x] Add toasts folder to main includes folder.
- [x] Create toast html files in toast folder.
- [x] Add messaging section to base to include toast based on message level
- [x] Add script to postloadjs section in base to show toasts
- [x] Add relevant toasts to sections of the code for adding, editing, deleting, errors etc.

**Comment by GaryDolan** [comment]
Toast notifications added and working correctly.
